// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: services/reports/api/report.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty message used as input for operations that don't require any input.
type EmptyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyRequest) Reset() {
	*x = EmptyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_reports_api_report_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyRequest) ProtoMessage() {}

func (x *EmptyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_reports_api_report_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyRequest.ProtoReflect.Descriptor instead.
func (*EmptyRequest) Descriptor() ([]byte, []int) {
	return file_services_reports_api_report_proto_rawDescGZIP(), []int{0}
}

// A trade report providing details of a specific trade for a financial instrument.
type LatestTrade struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"instrument_name"
	InstrumentName string `protobuf:"bytes,1,opt,name=instrument_name,json=instrumentName,proto3" json:"instrument_name"` // Name of the financial instrument.
	// @inject_tag: json:"date_en"
	DateEn string `protobuf:"bytes,2,opt,name=date_en,json=dateEn,proto3" json:"date_en"` // Date of the trade in EN format.
	// @inject_tag: json:"open"
	Open float64 `protobuf:"fixed64,3,opt,name=open,proto3" json:"open"` // Opening price of the trade.
	// @inject_tag: json:"high"
	High float64 `protobuf:"fixed64,4,opt,name=high,proto3" json:"high"` // Highest price during the trade.
	// @inject_tag: json:"low"
	Low float64 `protobuf:"fixed64,5,opt,name=low,proto3" json:"low"` // Lowest price during the trade.
	// @inject_tag: json:"close"
	Close float64 `protobuf:"fixed64,6,opt,name=close,proto3" json:"close"` // Closing price of the trade.
	// @inject_tag: json:"trade_id"
	TradeId int32 `protobuf:"varint,7,opt,name=trade_id,json=tradeId,proto3" json:"trade_id"` // ID of the trade
}

func (x *LatestTrade) Reset() {
	*x = LatestTrade{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_reports_api_report_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LatestTrade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestTrade) ProtoMessage() {}

func (x *LatestTrade) ProtoReflect() protoreflect.Message {
	mi := &file_services_reports_api_report_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestTrade.ProtoReflect.Descriptor instead.
func (*LatestTrade) Descriptor() ([]byte, []int) {
	return file_services_reports_api_report_proto_rawDescGZIP(), []int{1}
}

func (x *LatestTrade) GetInstrumentName() string {
	if x != nil {
		return x.InstrumentName
	}
	return ""
}

func (x *LatestTrade) GetDateEn() string {
	if x != nil {
		return x.DateEn
	}
	return ""
}

func (x *LatestTrade) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *LatestTrade) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *LatestTrade) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *LatestTrade) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *LatestTrade) GetTradeId() int32 {
	if x != nil {
		return x.TradeId
	}
	return 0
}

type TradesReport struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"latest_trades"
	LatestTrades []*LatestTrade `protobuf:"bytes,1,rep,name=latest_trades,json=latestTrades,proto3" json:"latest_trades"` // Latest trades
}

func (x *TradesReport) Reset() {
	*x = TradesReport{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_reports_api_report_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradesReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradesReport) ProtoMessage() {}

func (x *TradesReport) ProtoReflect() protoreflect.Message {
	mi := &file_services_reports_api_report_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradesReport.ProtoReflect.Descriptor instead.
func (*TradesReport) Descriptor() ([]byte, []int) {
	return file_services_reports_api_report_proto_rawDescGZIP(), []int{2}
}

func (x *TradesReport) GetLatestTrades() []*LatestTrade {
	if x != nil {
		return x.LatestTrades
	}
	return nil
}

var File_services_reports_api_report_proto protoreflect.FileDescriptor

var file_services_reports_api_report_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x72, 0x65, 0x70, 0x6f, 0x72,
	0x74, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x5f, 0x61, 0x70, 0x69,
	0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0xba, 0x01, 0x0a, 0x0b, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x54, 0x72, 0x61, 0x64, 0x65,
	0x12, 0x27, 0x0a, 0x0f, 0x69, 0x6e, 0x73, 0x74, 0x72, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x69, 0x6e, 0x73, 0x74, 0x72,
	0x75, 0x6d, 0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x61, 0x74,
	0x65, 0x5f, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x61, 0x74, 0x65,
	0x45, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f,
	0x77, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x63, 0x6c, 0x6f,
	0x73, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x72, 0x61, 0x64, 0x65, 0x49, 0x64, 0x22, 0x4d, 0x0a,
	0x0c, 0x54, 0x72, 0x61, 0x64, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x3d, 0x0a,
	0x0d, 0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x64, 0x65, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x5f, 0x61,
	0x70, 0x69, 0x2e, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x0c,
	0x6c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x54, 0x72, 0x61, 0x64, 0x65, 0x73, 0x32, 0x58, 0x0a, 0x0d,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x4c, 0x61, 0x74, 0x65, 0x73, 0x74, 0x54, 0x72, 0x61, 0x64, 0x65, 0x73,
	0x12, 0x19, 0x2e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x72, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x73,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x73, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_reports_api_report_proto_rawDescOnce sync.Once
	file_services_reports_api_report_proto_rawDescData = file_services_reports_api_report_proto_rawDesc
)

func file_services_reports_api_report_proto_rawDescGZIP() []byte {
	file_services_reports_api_report_proto_rawDescOnce.Do(func() {
		file_services_reports_api_report_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_reports_api_report_proto_rawDescData)
	})
	return file_services_reports_api_report_proto_rawDescData
}

var file_services_reports_api_report_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_services_reports_api_report_proto_goTypes = []interface{}{
	(*EmptyRequest)(nil), // 0: reports_api.EmptyRequest
	(*LatestTrade)(nil),  // 1: reports_api.LatestTrade
	(*TradesReport)(nil), // 2: reports_api.TradesReport
}
var file_services_reports_api_report_proto_depIdxs = []int32{
	1, // 0: reports_api.TradesReport.latest_trades:type_name -> reports_api.LatestTrade
	0, // 1: reports_api.ReportService.GetLatestTrades:input_type -> reports_api.EmptyRequest
	2, // 2: reports_api.ReportService.GetLatestTrades:output_type -> reports_api.TradesReport
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_services_reports_api_report_proto_init() }
func file_services_reports_api_report_proto_init() {
	if File_services_reports_api_report_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_reports_api_report_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_reports_api_report_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LatestTrade); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_reports_api_report_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradesReport); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_reports_api_report_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_reports_api_report_proto_goTypes,
		DependencyIndexes: file_services_reports_api_report_proto_depIdxs,
		MessageInfos:      file_services_reports_api_report_proto_msgTypes,
	}.Build()
	File_services_reports_api_report_proto = out.File
	file_services_reports_api_report_proto_rawDesc = nil
	file_services_reports_api_report_proto_goTypes = nil
	file_services_reports_api_report_proto_depIdxs = nil
}
