#!/bin/sh
if [ "${1}" = "" ]; then
  echo "formating all"
  go vet -vettool="$(which shadow)" ./...
  go fmt ./...
else
  echo "formating ${1}"
  go vet -vettool="$(which shadow)" ./services/"${1}"/...
  go fmt ./services/"${1}"/...
fi
